name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  buildTestRelease:

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        include:
          - os: windows-latest
            extension: ".zip"
            runtime: "win-x64"
            platform: "win"
          - os: ubuntu-latest
            extension: ".tar.gz"
            runtime: "linux-x64"
            platform: "linux"
          - os: macos-latest
            runtime: "osx-x64"
            extension: ".zip"
            platform: "osx"
        node_version: [16.x]
        dotnet_version: ['6.0.x']
      fail-fast: false

    runs-on: ${{ matrix.os }}

    env:
      DAEMON: '1.1.39'
      ARCH: 'x64'

    steps:

    - uses: actions/checkout@v1
      name: Checkout

    - name: Setup Node.js (${{ matrix.node_version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Variables
      run: |
        echo VERSION=$(npm run version --silent) >> $GITHUB_ENV
      shell: bash

    - name: Tooling
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install snapd
        sudo snap install --classic snapcraft

    - name: Download Blockcore Node
      shell: pwsh
      run: |
        echo ${env:PATH}
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        $url = "https://github.com/block-core/blockcore-nodes/releases/download/${{ env.DAEMON }}/MULTI-${{ env.DAEMON }}-${{ matrix.platform }}-${{ env.ARCH }}${{ matrix.extension }}"
        $output = Join-Path -Path "./" -ChildPath "daemon${{ matrix.extension }}"
        Write-Output "Url: $url"
        Write-Output "Path: $output"
        $start_time = Get-Date
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
        Write-Output "Time taken: $((Get-Date).Subtract($start_time).Seconds) second(s)"

    - name: Unpack (Windows)
      if: matrix.os == 'windows-latest'
      run: 7z x daemon${{ matrix.extension }} -odaemon

    - name: Unpack (Mac)
      if: matrix.os == 'macos-latest'
      run: unzip -a daemon${{ matrix.extension }} -d daemon

    - name: Unpack (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir daemon
        tar -xvzf daemon${{ matrix.extension }} -C daemon

    - name: Install (npm)
      run: npm ci

    - name: Build and Publish
      run: npm run publish:${{ matrix.platform }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
